//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jaeger.SAT.CFDI.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jaeger.SAT.CFDI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El emisor de la factura verificada se encuentra publicado en la lista de empresas que facturan operaciones simuladas de conformidad con los párrafos primero al quinto del Artículo 69-B del CFF.
        ///Consulta aquí la fecha en que se publicó la empresa en el listado de definitivas. Recuerda que, de conformidad con lo dispuesto por el octavo párrafo del artículo 69-B del CFF, si eres el receptor del 
        ///comprobante consultado y le has dado efectos fiscales, cuentas con 30 días contados a partir de la fecha de public [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string msg_100 {
            get {
                return ResourceManager.GetString("msg_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El RFC emisor y algún RFC a cuenta de terceros de la factura verificada, se encuentran publicados en la lista de empresas que facturan operaciones simuladas de conformidad con los párrafos primero al quinto del artículo 69-b del CFF.
        ///Consulta aquí la fecha en que se publicó la empresa en el listado de definitivas. Recuerda que, de conformidad con lo dispuesto por el octavo párrafo del artículo 69-B del CFF, si eres el receptor del comprobante consultado y le has dado efectos fiscales, cuentas con 30 días c [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string msg_101 {
            get {
                return ResourceManager.GetString("msg_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El RFC a cuenta de terceros de la factura verificada, se encuentran publicados en la lista de empresas que facturan operaciones simuladas de conformidad con los párrafos primero al quinto del artículo 69-b del CFF.
        ///Consulta aquí la fecha en que se publicaron las empresas en el listado de definitivas. Recuerda que, de conformidad con lo dispuesto por el octavo párrafo del artículo 69-B del CFF, si eres el receptor del comprobante consultado y le has dado efectos fiscales, cuentas con 30 días contados a part [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string msg_102 {
            get {
                return ResourceManager.GetString("msg_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para el supuesto en que tenga varios RFC relacionados a cuenta de terceros:
        ///Alguno de los RFC a cuenta de terceros de la factura verificada, se encuentra publicado en la lista de empresas que facturan operaciones simuladas de conformidad con los párrafos primero al quinto del artículo 69-b del CFF.
        ///Consulta aquí la fecha en que se publicaron las empresas en el listado de definitivas. Recuerda que, de conformidad con lo dispuesto por el octavo párrafo del artículo 69-B del CFF, si eres el receptor del comp [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string msg_103 {
            get {
                return ResourceManager.GetString("msg_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para el supuesto en que tenga varios RFC relacionados a cuenta de terceros:
        ///El RFC del emisor y alguno de los RFC a cuenta de terceros de la factura verificada, se encuentran publicados en la lista de empresas que facturan operaciones simuladas de conformidad con los párrafos primero al quinto del artículo 69-b del CFF.
        ///Consulta aquí la fecha en que se publicaron las empresas en el listado de definitivas. Recuerda que, de conformidad con lo dispuesto por el octavo párrafo del artículo 69-B del CFF, si ere [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string msg_104 {
            get {
                return ResourceManager.GetString("msg_104", resourceCulture);
            }
        }
    }
}
